apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokun
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tokun
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tokun
    spec:
      containers:
        - name: tokun
          image: ${CONTAINER_IMAGE_TAGGED}
          envFrom:
            - secretRef:
                name: tokun-env-from-vault
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tokun
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tokun
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tokun
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Tokun
    gethomepage.dev/icon: mdi-ideogram-cjk
    gethomepage.dev/group: 1P

spec:
  tls:
    - hosts:
        - tokun.home.maximemoreillon.com
      secretName: tokun-tls
  rules:
    - host: tokun.home.maximemoreillon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tokun
                port:
                  number: 3000
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tokun-env
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tokun-env-from-vault
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: tokun
